export const translations= {
    en: {
      home: 'Home',
      category: 'Category',
      singleNews: 'Single News',
      contact: 'Contact',
      featuredNews : 'Feature News',
      advertisement: 'Advertisement',
      newsletter: 'Newsletter',
      tags:'Tags',
      followUs:'Follow Us',
      follower:'Followers',
      contact_question: ' Contact Us For Any Quesion',
      contact_info:'Contact Info',
      contact_content: `You can contact us anytime for more information about our team, our mission, or the work we do. We are always happy to connect, answer your questions, and listen to your feedback. As students from FPT University, we are committed to constantly improving and providing you with the best user experience possible. We truly hope you enjoy exploring and using our website as much as we enjoyed building it.`,
      contact_from:'We from',
      contact_place:'FPT University, Da Nang, Viet Nam',
      contact_email:'Email Us',
      contact_form:'Send feedback',
      contact_form_name:'Your name',
      contact_form_subject:'Subject',
      contact_form_message:'Message',
      contact_form_send_message:'Send Message',
      view_all:'View All',
      breaking_news:'Breaking News',
    },
    vi: {
      home: 'Trang chủ',
      category: 'Thể loại',
      singleNews: 'Tin chi tiết',
      contact: 'Liên hệ',
      featuredNews :'Tin tức nổi bật',
      advertisement: 'Quảng cáo',
      newsletter: 'Đăng kí bản tin',
      tags:'Thể loại',
      followUs:'Theo dõi chúng tôi',
      follower:'Người theo dõi',
      contact_question: 'Liên hệ chúng tôi với bất kỳ thắc mắc nào',
      contact_info:'Thông tin liên hệ',
      contact_content: `Bạn có thể liên hệ với chúng tôi bất cứ lúc nào để biết thêm thông tin về nhóm của chúng tôi, sứ mệnh của chúng tôi hoặc công việc chúng tôi làm. Chúng tôi luôn sẵn lòng kết nối, trả lời các câu hỏi của bạn và lắng nghe phản hồi của bạn. Là sinh viên của Đại học FPT, chúng tôi cam kết liên tục cải thiện và cung cấp cho bạn trải nghiệm người dùng tốt nhất có thể. Chúng tôi thực sự hy vọng bạn thích khám phá và sử dụng trang web của chúng tôi nhiều như chúng tôi thích xây dựng nó.`,
      contact_from:'Chúng tôi đến từ',
      contact_place:'Đại học FPT, Đà Nẵng, Việt Nam',
      contact_email:'Gửi mail cho chúng tôi',
      contact_form:'Gửi phản hồi',
      contact_form_name:'Tên của bạn',
      contact_form_subject:'Tiêu đề',
      contact_form_message:'Nội dung',
      contact_form_send_message:'Gửi',
      view_all:'Xem tất cả',
      breaking_news:'Tin nóng',

    },
  };
  